using UnityEngine;

namespace MotoSquid.Track
{
    // A reference line for one real road, to build an EasyRoads3D road over. Lives under an EditorOnly
    // root, so it never ships. Generated by RoadGuideImporter: rebuilding the guides replaces it.
    public class RoadGuide : MonoBehaviour
    {
        public string vicmapId;
        public string roadName;
        public int roadClass;          // 0 freeway, 1 highway
        public int lanes;              // in the direction of travel for one-way roads, both ways otherwise
        public bool lanesFromOsm;      // false: guessed from the road type, OSM had no lanes tag here
        public bool oneWay;
        public string divided;         // Vicmap div_rd: DD divided carriageway, ND not divided
        public string structure;       // road, bridge or tunnel
        public Vector3[] points;
        public float scale = 1f;       // the preview scale the guides were built at

#if UNITY_EDITOR
        void OnDrawGizmosSelected()
        {
            if (points == null || points.Length < 2) return;
            Gizmos.color = Color.white;
            float step = 0f;
            for (int i = 1; i < points.Length; i++)
            {
                step += Vector3.Distance(points[i - 1], points[i]);
                if (!oneWay || step < 40f * scale) continue;
                step = 0f;
                Vector3 dir = (points[i] - points[i - 1]).normalized;
                Vector3 side = Vector3.Cross(Vector3.up, dir) * 2f * scale;
                Vector3 tip = points[i] + Vector3.up * 0.5f * scale;
                Gizmos.DrawLine(tip, tip - dir * 4f * scale + side);
                Gizmos.DrawLine(tip, tip - dir * 4f * scale - side);
            }
            string lanesText = lanesFromOsm ? $"{lanes} lanes" : $"{lanes} lanes (guessed)";
            UnityEditor.Handles.Label(points[points.Length / 2] + Vector3.up * 3f * scale,
                $"{roadName}\n{lanesText}{(oneWay ? ", one-way" : "")}, {structure}");
        }
#endif
    }
}
